/**
 * Samples Parser — Unit Tests
 *
 * Verifies the SLIMS "Content record" sample template is parsed correctly:
 *  - 3-row header (config + machine keys + human labels) is handled
 *  - requested field renames are applied (Barcode → sample_id, etc.)
 *  - European dates (DD/MM/YYYY) normalise to ISO YYYY-MM-DD
 *  - every raw SLIMS column is preserved in metadata (nothing lost)
 *  - empty cells become null and chemical_ids defaults to []
 *
 * The parser exposes parseSamplesRows(aoa) so we can test the mapping
 * logic without constructing a binary .xlsx.
 */
const {
  parseSamplesRows,
  mapRowToSample,
  normalizeDate
} = require('../src/utils/samplesParser');

// ─── Fixture: array-of-arrays mirroring the real SLIMS workbook ─────────────
// Row 1: config blob + banner   Row 2: machine keys   Row 3: human labels   Row 4+: data
const KEY_ROW = [
  'cntn_fk_contentType', '<SLIMSGUID>', 'cntn_fk_category', 'cntn_cf_fk_sampleSubtype',
  'cntn_cf_fk_responsible', 'cntn_cf_fk_ownerGroup', 'cntn_id', 'cntn_cf_description',
  'cntn_cf_fk_project', 'cntn_fk_status', 'cntn_barCode', 'cntn_cf_receptionDate',
  'cntn_fk_provider', 'cntn_fk_location', 'cntn_cf_doc', 'cntn_cf_loc',
  'derivedCount', 'cntn_cf_exp_date'
];
const LABEL_ROW = [
  'Content Type * (cntp_name)', '<SLIMSGUID>', 'Category (cntp_name)', 'Sample Subtype (rdrc_name)',
  'Responsible (contact person) * (user_userName)', 'Owner Group * (grps_groupName)', 'Id *', 'Description',
  'NPDI number Project (Study) * (cntn_cf_studyProjectComposite)', 'Status * (stts_name)', 'Barcode', 'Reception Date',
  'Provider (prvd_name)', 'Location (cntn_id)', 'DOC', 'LOC',
  'Derived Count', 'Expiry date'
];
const CONFIG_ROW = ['{"timezone":"Europe/Zurich"}', '', '', '', 'Excel template generated by SLIMS'];

const DATA_ROW = [
  'Pack - Material', '692caa0a-d254-4477-8b56-735a04fb9d8a', 'Packaging', 'Polymer',
  'RDKosterSa', 'NIPS - Advanced Packaging Sciences and Sustainability', 'Ulterion 529HS coated on Alu',
  'Supplier JainChem\nUlterion 529 HS coated on Alufoil (6 gsm)',
  'DUND-103291 Buddy (buddy)', 'Available', 'PIPM00617', '01/05/2023',
  'Irrelevant', 'K29', 'FALSE', 'FALSE', '0', ''
];

const AOA = [CONFIG_ROW, KEY_ROW, LABEL_ROW, DATA_ROW];

describe('parseSamplesRows — header detection', () => {
  test('locates the SLIMS machine-key row and returns one data record', () => {
    const { records, keyRowIndex } = parseSamplesRows(AOA);
    expect(keyRowIndex).toBe(1);
    expect(records).toHaveLength(1);
  });

  test('keys the record by SLIMS machine keys and captures labels', () => {
    const { records } = parseSamplesRows(AOA);
    const r = records[0];
    expect(r['cntn_barCode']).toBe('PIPM00617');
    expect(r['cntn_id']).toBe('Ulterion 529HS coated on Alu');
    expect(r._labels['cntn_barCode']).toBe('Barcode');
    expect(r._rowNumber).toBe(4);
  });

  test('skips fully blank rows', () => {
    const withBlank = [...AOA, ['', '', '', '', '', '', '', '', '', '', '', '']];
    const { records } = parseSamplesRows(withBlank);
    expect(records).toHaveLength(1);
  });

  test('handles a plain single-header sheet as a fallback', () => {
    const plain = [
      ['cntn_barCode', 'cntn_id', 'cntn_fk_category'],
      ['SMP-1', 'Widget', 'Packaging']
    ];
    const { records } = parseSamplesRows(plain);
    expect(records).toHaveLength(1);
    expect(records[0]['cntn_barCode']).toBe('SMP-1');
  });
});

describe('mapRowToSample — field renames', () => {
  const sample = mapRowToSample(parseSamplesRows(AOA).records[0]);

  test('Barcode → sample_id', () => expect(sample.sample_id).toBe('PIPM00617'));
  test('Id → identification', () => expect(sample.identification).toBe('Ulterion 529HS coated on Alu'));
  test('Category → content_type', () => expect(sample.content_type).toBe('Packaging'));
  test('Sample Subtype → material_type', () => expect(sample.material_type).toBe('Polymer'));
  test('Responsible → responsible_person', () => expect(sample.responsible_person).toBe('RDKosterSa'));
  test('Owner Group → group_name', () =>
    expect(sample.group_name).toBe('NIPS - Advanced Packaging Sciences and Sustainability'));
  test('NPDI Project → project_number', () => expect(sample.project_number).toBe('DUND-103291 Buddy (buddy)'));
  test('Description → description (newlines preserved)', () =>
    expect(sample.description).toContain('Supplier JainChem'));

  test('name falls back to identification for UI/search', () =>
    expect(sample.name).toBe('Ulterion 529HS coated on Alu'));

  test('status is lower-cased/underscored', () => expect(sample.status).toBe('available'));
});

describe('mapRowToSample — cleaning & derived', () => {
  const sample = mapRowToSample(parseSamplesRows(AOA).records[0]);

  test('Reception Date normalised DD/MM/YYYY → ISO', () =>
    expect(sample.reception_date).toBe('2023-05-01'));

  test('empty Expiry date → null', () => expect(sample.expiry_date).toBeNull());

  test('chemical_ids defaults to an empty array', () =>
    expect(sample.chemical_ids).toEqual([]));

  test('metadata preserves every raw SLIMS column verbatim', () => {
    expect(sample.metadata['cntn_barCode']).toBe('PIPM00617');
    expect(sample.metadata['cntn_fk_provider']).toBe('Irrelevant');
    expect(sample.metadata['cntn_fk_location']).toBe('K29');
    expect(sample.metadata['cntn_cf_doc']).toBe('FALSE');
    // Empty raw cells become null in metadata.
    expect(sample.metadata['cntn_cf_exp_date']).toBeNull();
  });

  test('human labels are retained for reference', () =>
    expect(sample.labels['cntn_id']).toBe('Id *'));

  test('warns when sample_id (Barcode) is missing', () => {
    const noBarcode = parseSamplesRows(AOA).records[0];
    delete noBarcode['cntn_barCode'];
    const mapped = mapRowToSample(noBarcode);
    expect(mapped.sample_id).toBeNull();
    expect(mapped._warnings.join(' ')).toMatch(/Barcode/i);
  });
});

describe('normalizeDate', () => {
  test('DD/MM/YYYY → ISO', () => expect(normalizeDate('01/05/2023')).toBe('2023-05-01'));
  test('DD-MM-YYYY → ISO', () => expect(normalizeDate('9-1-2026')).toBe('2026-01-09'));
  test('already-ISO passes through', () => expect(normalizeDate('2023-05-01')).toBe('2023-05-01'));
  test('blank → null', () => expect(normalizeDate('')).toBeNull());
  test('2-digit year expands', () => expect(normalizeDate('05/05/23')).toBe('2023-05-05'));
});
